export const GET_CITIES_SUGGESTIONS = 'GET_CITIES_SUGGESTIONS';
export const GET_CITIES_FROM_STORAGE = 'GET_CITIES_FROM_STORAGE';
export const ADD_CITY = 'ADD_CITY';
export const DELETE_CITY = 'DELETE_CITY';
export const REFRESH_CITY = 'REFRESH_CITY';